services:

  emailenv:

    build: .

    container_name: emailenv

    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_GEMINI_API_KEY=${NEXT_PUBLIC_GEMINI_API_KEY}

    expose:
      - "3000"

    networks:
      - emailenv-network


  nginx:

    image: nginx:alpine

    container_name: emailenv-nginx

    restart: unless-stopped

    depends_on:
      - emailenv

    ports:
      - "5190:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

    networks:
      - emailenv-network


networks:
  emailenv-network: